import type { OAuth2Tokens } from "better-auth/oauth2";
import type {
	BaseOAuthProviderOptions,
	GenericOAuthConfig,
	GenericOAuthUserInfo,
} from "better-auth/plugins/generic-oauth";
import { decodeJwt } from "jose";

const DISCOVERY_URL =
	"https://auth.agentid.com/.well-known/openid-configuration";
const USER_INFO_URL = "https://auth.agentid.com/v0/userinfo";
const DEFAULT_SCOPES = ["openid", "email", "profile"];

/** Options for the AgentID Generic OAuth provider helper. */
export interface AgentIdOptions
	extends Omit<
		BaseOAuthProviderOptions,
		"clientSecret" | "pkce" | "tokenEndpointAuth"
	> {
	/** Client secret generated by the AgentID console. */
	clientSecret: string;
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

function nonEmptyString(value: unknown): value is string {
	return typeof value === "string" && value.length > 0;
}

function fallbackName(email: string): string {
	return email.split("@", 1)[0] || email;
}

async function getAgentIdUserInfo(
	tokens: OAuth2Tokens,
): Promise<GenericOAuthUserInfo | null> {
	if (!tokens.accessToken || !tokens.idToken) return null;

	try {
		const expectedSubject = decodeJwt(tokens.idToken).sub;
		if (!nonEmptyString(expectedSubject)) return null;

		const response = await fetch(USER_INFO_URL, {
			headers: { Authorization: `Bearer ${tokens.accessToken}` },
		});
		if (!response.ok) return null;

		const body: unknown = await response.json();
		if (
			!isRecord(body) ||
			body.sub !== expectedSubject ||
			!nonEmptyString(body.email)
		) {
			return null;
		}

		return {
			...body,
			sub: expectedSubject,
			email: body.email,
			emailVerified: body.email_verified === true,
			name: nonEmptyString(body.name) ? body.name : fallbackName(body.email),
		};
	} catch {
		return null;
	}
}

/**
 * Create an AgentID configuration for Better Auth's Generic OAuth plugin.
 *
 * AgentID requires S256 PKCE and registered clients use HTTP Basic token
 * endpoint authentication. AgentID does not echo an OIDC nonce, so this helper
 * relies on PKCE while retaining ID-token signature, issuer, and audience
 * verification through discovery.
 */
export function agentid(
	options: AgentIdOptions,
): GenericOAuthConfig<"agentid"> {
	return {
		providerId: "agentid",
		name: "AgentID",
		discoveryUrl: DISCOVERY_URL,
		requireIdTokenVerification: true,
		disableIdTokenNonceBinding: true,
		clientId: options.clientId,
		clientSecret: options.clientSecret,
		tokenEndpointAuth: { method: "client_secret_basic" },
		scopes: options.scopes ?? [...DEFAULT_SCOPES],
		redirectURI: options.redirectURI,
		endSessionEndpoint: options.endSessionEndpoint,
		postLogoutRedirectURI: options.postLogoutRedirectURI,
		disableProviderLogout: options.disableProviderLogout,
		pkce: true,
		disableImplicitSignUp: options.disableImplicitSignUp,
		disableSignUp: options.disableSignUp,
		overrideUserInfo: options.overrideUserInfo,
		getUserInfo: getAgentIdUserInfo,
	};
}
